// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLwalgkvQhf-rTMRV8XGH5hDfecO9p3A',
    appId: '1:670036670378:web:03eda333edbda0bd151dd3',
    messagingSenderId: '670036670378',
    projectId: 'flutter-clean-arch-2026',
    authDomain: 'flutter-clean-arch-2026.firebaseapp.com',
    storageBucket: 'flutter-clean-arch-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3ZE94Edr8qRARQIYAR-nKrEGrTLffhA',
    appId: '1:670036670378:android:2ebd6f4334981199151dd3',
    messagingSenderId: '670036670378',
    projectId: 'flutter-clean-arch-2026',
    storageBucket: 'flutter-clean-arch-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrs2MNF5pcaHf-nhw3naRfC611oeviIDU',
    appId: '1:670036670378:ios:63744dcfb9f6c82e151dd3',
    messagingSenderId: '670036670378',
    projectId: 'flutter-clean-arch-2026',
    storageBucket: 'flutter-clean-arch-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterCleanArchitectureTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrs2MNF5pcaHf-nhw3naRfC611oeviIDU',
    appId: '1:670036670378:ios:63744dcfb9f6c82e151dd3',
    messagingSenderId: '670036670378',
    projectId: 'flutter-clean-arch-2026',
    storageBucket: 'flutter-clean-arch-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterCleanArchitectureTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNLwalgkvQhf-rTMRV8XGH5hDfecO9p3A',
    appId: '1:670036670378:web:9d9efc4d13dc9c01151dd3',
    messagingSenderId: '670036670378',
    projectId: 'flutter-clean-arch-2026',
    authDomain: 'flutter-clean-arch-2026.firebaseapp.com',
    storageBucket: 'flutter-clean-arch-2026.firebasestorage.app',
  );
}
